### ISSUE TITLE
Expected output kræver mindre end eller lig med sammenligning

### ISSUE THREAD

**Issue by rasmusfreund** [birc-ctib-2022/bed-1-freund#2]
Beskrivelsen under "Slicing genomic features" udtrykker at:
> all features on chromosome chrom between chromStart and chromEnd, with chromStart included and chromEnd excluded

Expected-#.txt filerne indeholder dog  features som kræver at chromEnd er inkluderet. De features som kræver at End er inkluderet, er:

Expected-1.txt:
chrom0	984	985	Feature-47
chrom5	981	982	Feature-700
chrom2	563	564	Feature-593

Expected-2.txt:
chrom3	981	982	Feature-208

Expected-3.txt:
chrom4	937	938	Feature-830

Jeg har vedhæftet filerne som indeholder outputtet fra kode som søger end-eksklusivt hvis du selv vil dobbelt-tjekke.

[actual-out1.txt](https://github.com/birc-ctib-2022/bed-1-freund/files/9744101/actual-out1.txt)
[actual-out2.txt](https://github.com/birc-ctib-2022/bed-1-freund/files/9744102/actual-out2.txt)
[actual-out3.txt](https://github.com/birc-ctib-2022/bed-1-freund/files/9744103/actual-out3.txt)

**Comment by mailund** [comment]
Jeg tjekkede med min version der tager start med og ikke slutningen

```python
        for feature in table.get_chrom(chrom):
            if start <= feature.chrom_start < end:
                print_line(feature, args.outfile)
```

og den får de forventede filer.

Når jeg kikker på jeres kode

```python
        for k in chrom:
            if  queryPositionStart <= k.chrom_start and queryPositionEnd >= k.chrom_end:
                final_out.append(k)
```

tror jeg at problemet er definitionen af et overlap. I vil have at regionen i bed-filen er indeholdt i query, men det er nok hvis den overlapper. Er det ikke korrekt?

**Comment by rasmusfreund** [comment]
Det har du da fuldstændigt ret i Thomas, det er mig der har set forkert. Beklager!

**Comment by mailund** [comment]
Ikke noget problem. Det var godt at få tjekket!
